make -j 5 -k -f bin/Makefile
make -j 5 -k -f conf/Makefile
make -j 5 -k -f etc/Makefile
make -j 5 -k -f kernel/USRSYS/Makefile
make -j 5 -k -f lib/Makefile
make -j 5 -k -f usr/bin/Makefile
make -j 5 -k -f usr/dict/Makefile
make -j 5 -k -f usr/games/Makefile
make -j 5 -k -f usr/lib/Makefile
make -j 5 -k -f usr/pub/Makefile
make -j 5 -k -f usr/src/Makefile